name: Build, Analyze and Deploy
on:
    push:
        branches:
            - master

jobs:
    build-analyze-deploy:
        runs-on: self-hosted

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Rust setup
              uses: dtolnay/rust-toolchain@stable

            - name: Rust cache
              uses: swatinem/rust-cache@v2
              with:
                workspaces: 'src-tauri -> target'

            - name: Set nodeJS
              uses: actions/setup-node@v3
              with:
                node-version: 'lts/*'

            - name: Set YARN
              uses: borales/actions-yarn@v4
              with:
                cmd: install

            - name: YARN cache
              uses: c-hive/gha-yarn-cache@v2

            - name: Install wasm-pack
              run: cargo install wasm-pack

            - name: Install NPM dependencies
              run: npm install

            - name: Create Solana development environment
              run: |
                sudo chmod +x install-solana-anchor-and-soda.sh
                ./install-solana-anchor-and-soda.sh